apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tensor-fusion-hypervisor-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tensor-fusion-hypervisor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tensor-fusion-hypervisor-role
subjects:
- kind: ServiceAccount
  name: tensor-fusion-hypervisor-sa
  namespace: {{ include "tensor-fusion.namespace" . }}